services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    Harmony\Bundle\RoutingBundle\Doctrine\Orm\ContentRepository: ~
    harmony_routing.content_repository: '@Harmony\Bundle\RoutingBundle\Doctrine\Orm\ContentRepository'

    harmony_routing.orm_candidates:
        class: Symfony\Cmf\Component\Routing\Candidates\Candidates
        arguments:
            $locales: '%harmony_routing.dynamic.locales%'
            $limit: '%harmony_routing.dynamic.limit_candidates%'

    Harmony\Bundle\RoutingBundle\Doctrine\Orm\RouteProvider:
        arguments:
            $candidatesStrategy: '@harmony_routing.orm_candidates'
        calls:
            - [setRouteCollectionLimit, ['%harmony_routing.route_collection_limit%']]
    harmony_routing.route_provider: '@Harmony\Bundle\RoutingBundle\Doctrine\Orm\RouteProvider'