services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    Harmony\Bundle\RoutingBundle\Doctrine\MongoDB\ContentRepository:
        calls:
            - [setManagerName, ['%harmony_routing.dynamic.persistence.mongodb.manager_name%']]
    harmony_routing.content_repository: '@Harmony\Bundle\RoutingBundle\Doctrine\MongoDB\ContentRepository'

    harmony_routing.mongodb_candidates:
        class: Symfony\Cmf\Component\Routing\Candidates\Candidates
        arguments:
            $locales: '%harmony_routing.dynamic.locales%'
            $limit: '%harmony_routing.dynamic.limit_candidates%'

    Harmony\Bundle\RoutingBundle\Doctrine\MongoDB\RouteProvider:
        arguments:
            $candidatesStrategy: '@harmony_routing.mongodb_candidates'
        calls:
            - [setManagerName, ['%harmony_routing.dynamic.persistence.mongodb.manager_name%']]
            - [setRouteCollectionLimit, ['%harmony_routing.route_collection_limit%']]
    harmony_routing.route_provider: '@Harmony\Bundle\RoutingBundle\Doctrine\MongoDB\RouteProvider'