parameters:
    harmony_routing.uri_filter_regexp: null

services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    harmony_routing.enhancer.route_content:
        class: Symfony\Cmf\Component\Routing\Enhancer\RouteContentEnhancer
        tags:
            - { name: dynamic_router_route_enhancer, priority: 100 }
        arguments:
            $routefield: _route_object
            $target: _content

    harmony_routing.enhancer.default_controller:
        class: Symfony\Cmf\Component\Routing\Enhancer\FieldPresenceEnhancer
        arguments:
            $source: null
            $target: _controller
            $value: '%harmony_routing.default_controller%'

    harmony_routing.enhancer.explicit_template:
        class: Symfony\Cmf\Component\Routing\Enhancer\FieldPresenceEnhancer
        arguments:
            $source: _template
            $target: _controller
            $value: '%harmony_routing.generic_controller%'

    harmony_routing.enhancer.controllers_by_type:
        class: Symfony\Cmf\Component\Routing\Enhancer\FieldMapEnhancer
        arguments:
            $source: type
            $target: _controller
            $hashmap: '%harmony_routing.controllers_by_type%'

    harmony_routing.enhancer.controllers_by_class:
        class: Symfony\Cmf\Component\Routing\Enhancer\FieldByClassEnhancer
        arguments:
            $source: _content
            $target: _controller
            $map: '%harmony_routing.controllers_by_class%'

    harmony_routing.enhancer.controller_for_templates_by_class:
        class: Symfony\Cmf\Component\Routing\Enhancer\FieldByClassEnhancer
        arguments:
            $source: _content
            $target: _controller
            $map: {  }

    harmony_routing.enhancer.templates_by_class:
        class: Symfony\Cmf\Component\Routing\Enhancer\FieldByClassEnhancer
        arguments:
            $source: _content
            $target: _template
            $map: '%harmony_routing.templates_by_class%'

    harmony_routing.enhancer.content_repository:
        class: Symfony\Cmf\Component\Routing\Enhancer\ContentRepositoryEnhancer
        arguments:
            $contentRepository: '@harmony_routing.content_repository'

    Harmony\Bundle\RoutingBundle\Routing\DynamicRouter:
        arguments:
            $context: '@router.request_context'
            $matcher: '@harmony_routing.nested_matcher'
            $generator: ''
            $uriFilterRegexp: '%harmony_routing.uri_filter_regexp%'
            $eventDispatcher: '@?event_dispatcher'
            $provider: '@harmony_routing.route_provider'
        calls:
            - [setRequestStack, ['@request_stack']]

    Harmony\Bundle\RoutingBundle\Routing\RedirectRouter: ~

    harmony_routing.nested_matcher:
        class: Symfony\Cmf\Component\Routing\NestedMatcher\NestedMatcher
        arguments:
            $provider: '@harmony_routing.route_provider'
            $final: '@harmony_routing.final_matcher'

    harmony_routing.matcher.dummy_collection:
        class: Symfony\Component\Routing\RouteCollection

    harmony_routing.matcher.dummy_context:
        class: Symfony\Component\Routing\RequestContext

    harmony_routing.final_matcher:
        class: Symfony\Cmf\Component\Routing\NestedMatcher\UrlMatcher
        arguments:
            $routes: '@harmony_routing.matcher.dummy_collection'
            $context: '@harmony_routing.matcher.dummy_context'

    harmony_routing.generator:
        class: Symfony\Cmf\Component\Routing\ContentAwareGenerator
        arguments:
            $provider: '@harmony_routing.route_provider'

    Harmony\Bundle\RoutingBundle\Controller\RedirectController:
        tags: ['controller.service_arguments']

    Harmony\Bundle\RoutingBundle\Doctrine\RouteConditionMetadataListener:
        tags:
            - { name: doctrine.event_subscriber }
            - { name: doctrine_mongodb.odm.event_subscriber }